apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    openshift.io/host.generated: "true"
  labels:
    app: backend-app
  name: backend-app
  namespace: captaintcs
spec:
  host: backend-app-captaintcs.redhat-hackathon-ocp-a39cdf59c11fe9ef74002319618f3999-0000.eu-gb.containers.appdomain.cloud
  port:
    targetPort: 8080
  to:
    kind: Service
    name: backend-app
    weight: 100
  wildcardPolicy: None
status:
  ingress:
  - conditions:
    - lastTransitionTime: "2020-10-24T14:56:05Z"
      status: "True"
      type: Admitted
    host: backend-app-captaintcs.redhat-hackathon-ocp-a39cdf59c11fe9ef74002319618f3999-0000.eu-gb.containers.appdomain.cloud
    routerCanonicalHostname: redhat-hackathon-ocp-a39cdf59c11fe9ef74002319618f3999-0000.eu-gb.containers.appdomain.cloud
    routerName: default
    wildcardPolicy: None
