apiVersion: v1
kind: Service
metadata:
  labels:
    app: backend-app
  name: backend-app
  namespace: captaintcs
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: backend-app
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
